### ISSUE TITLE
when I using cmake to build the SUCHAI, there is a error about cannot find csp.h, Would you please tell me how to fix that?

### ISSUE THREAD

**Issue by fzmeng8** [spel-uchile/SUCHAI-Flight-Software#17]
![cmake](https://github.com/user-attachments/assets/e382e0f6-07c2-4a99-95d7-fade2d224e10)

**Comment by carlgonz** [comment]
Hi! Thanks for reporting this issue. Some thoughts

- This repository is just a mirror, the main development is happening in the GitLab repository: https://gitlab.com/spel-uchile/suchai-flight-software/
- I recommend using the [feature/framework-sim](https://gitlab.com/spel-uchile/suchai-flight-software/-/tree/feature/framework-sim) branch which have less external requirements.
- The issue you mention might be related to not being building the libcsp which is a requirement. The problem is that to build the libcsp you need python2 availabl, and that is not the default in latest Ubuntu versions for example. I'd recommend setting up a python2 environment in your session before building. I usually use [pyenv](https://github.com/pyenv/pyenv) for this.

I hope this helps.

Best,
Carlos.
